name: dospace
description: Client library to interact with the DigitalOcean Spaces API. Same API as Amazon AWS S3.
version: 0.13.15
homepage: https://github.com/nbspou/dospace


environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  xml: ^6.3.0
  http: ^1.2.1
  crypto: ^3.0.6

